run:
  timeout: 1m
  tests: true

  skip-dirs-use-default: true
  skip-dirs:
    - bin
    - \.git

linters:
  enable:
    - bodyclose
    - dupl
    - goconst
    - gocyclo
    - gocognit
    - gocritic
    - gofmt
    - errorlint
    - nakedret
    - nestif
    - prealloc
    - predeclared
    - stylecheck
    - unconvert
    - unparam

output:
  format: colored-line-number
