{
 "title": "App",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Server RPS",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_total{handler!=\"/metrics\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server RPS by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(handler, method) (rate(http_server_requests_total{handler!=\"/metrics\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server code 500 increase by endpoint/Minute",
   "type": "timeseries",
   "description": "Изменение количества ошибок по эндпоинтам",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(http_server_requests_total{status=\"500\"}[1m])",
     "legendFormat": "{{handler}} - {{method}}"
    }
   ]
  },
  {
   "title": "Server latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_server_request_duration_seconds_bucket{handler!=\"/metrics\"}[1m])))",
     "legendFormat": "Q99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_server_request_duration_seconds_bucket{handler!=\"/metrics\"}[1m])))",
     "legendFormat": "Q95"
    },
    {
     "expr": "histogram_quantile(0.50, sum by(le) (rate(http_server_request_duration_seconds_bucket{handler!=\"/metrics\"}[1m])))",
     "legendFormat": "Q50"
    }
   ]
  },
  {
   "title": "Server latensy by endpoint (quantile 0.99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, handler, method) (rate(http_server_request_duration_seconds_bucket{handler!=\"/metrics\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Thread service RPS by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(handler, method) (rate(http_services_requests_total{host=\"vk-golang.ru:15000\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Comment service RPS by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(handler, method) (rate(http_services_requests_total{host=\"vk-golang.ru:16000\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Auth service RPS by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(handler, method) (rate(http_services_requests_total{host=\"vk-golang.ru:17000\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Thread service code 500 increase by endpoint/Minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(handler, method) (increase(http_services_requests_total{host=\"vk-golang.ru:15000\", status=\"500\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Comment service code 500 increase by endpoint/Minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(handler, method) (increase(http_services_requests_total{host=\"vk-golang.ru:16000\", status=\"500\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Auth service code 500 increase by endpoint/Minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(handler, method) (increase(http_services_requests_total{host=\"vk-golang.ru:17000\", status=\"500\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Thread service latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_services_request_duration_seconds_bucket{host=\"vk-golang.ru:15000\"}[1m])))",
     "legendFormat": "Q99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_services_request_duration_seconds_bucket{host=\"vk-golang.ru:15000\"}[1m])))",
     "legendFormat": "Q95"
    },
    {
     "expr": "histogram_quantile(0.50, sum by(le) (rate(http_services_request_duration_seconds_bucket{host=\"vk-golang.ru:15000\"}[1m])))",
     "legendFormat": "Q50"
    }
   ]
  },
  {
   "title": "Comment service latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_services_request_duration_seconds_bucket{host=\"vk-golang.ru:16000\"}[1m])))",
     "legendFormat": "Q99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_services_request_duration_seconds_bucket{host=\"vk-golang.ru:16000\"}[1m])))",
     "legendFormat": "Q95"
    },
    {
     "expr": "histogram_quantile(0.50, sum by(le) (rate(http_services_request_duration_seconds_bucket{host=\"vk-golang.ru:16000\"}[1m])))",
     "legendFormat": "Q50"
    }
   ]
  },
  {
   "title": "Auth service latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_services_request_duration_seconds_bucket{host=\"vk-golang.ru:17000\"}[1m])))",
     "legendFormat": "Q99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_services_request_duration_seconds_bucket{host=\"vk-golang.ru:17000\"}[1m])))",
     "legendFormat": "Q95"
    },
    {
     "expr": "histogram_quantile(0.50, sum by(le) (rate(http_services_request_duration_seconds_bucket{host=\"vk-golang.ru:17000\"}[1m])))",
     "legendFormat": "Q50"
    }
   ]
  },
  {
   "title": "Thread service percentage of requests with latency <= 10ms (SLA)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(handler, method)(increase(http_services_request_duration_seconds_bucket{le=\"0.01\", host=\"vk-golang.ru:15000\"}[1m])) / sum by(handler, method)(increase(http_services_request_duration_seconds_bucket{le=\"+Inf\", host=\"vk-golang.ru:15000\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Comment service percentage of requests with latency <= 20ms (SLA)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(handler, method)(increase(http_services_request_duration_seconds_bucket{le=\"0.02\", host=\"vk-golang.ru:16000\"}[1m])) / sum by(handler, method)(increase(http_services_request_duration_seconds_bucket{le=\"+Inf\", host=\"vk-golang.ru:16000\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Auth service percentage of requests with latency <= 5ms (SLA)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(handler, method)(increase(http_services_request_duration_seconds_bucket{le=\"0.005\", host=\"vk-golang.ru:17000\"}[1m])) / sum by(handler, method)(increase(http_services_request_duration_seconds_bucket{le=\"+Inf\", host=\"vk-golang.ru:17000\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}