global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'golang'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8000']

  # - job_name: 'system'
  #   scrape_interval: 20s
  #   static_configs:
  #     - targets: ['node-exporter:9100']

